import { CartProvider } from "@/context/CartContext";
import Footer from "../components/Footer";
import Header from "../components/Header";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`h-full antialiased `}
    >
      <body className="min-h-full flex flex-col font-sans">
        <CartProvider>
          <Header />
          <Toaster
            position="bottom-center"
            reverseOrder={false}
            gutter={8}
            containerClassName=""
            containerStyle={{}}
            toastOptions={{
              duration: 3000,
              style: {
                background: '#363636',
                color: '#fff',
              },
            }}
          />
          <main className="">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}